name: Build AATHVIK APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AATHVIK source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build AATHVIK Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload AATHVIK APK
        uses: actions/upload-artifact@v4
        with:
          name: AATHVIK-V16-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
